### ISSUE TITLE
Latest docker image 0.3.1 does not work

### ISSUE THREAD

**Issue by botzill** [sstarcher/helm-exporter#11]
Hi.

Can you make an update to helm chart and update latest image? Also, I tried it and seems that does not work, I get this error:

```
Readiness probe failed: Get http://10.244.1.112:9100/metrics: dial tcp 10.244.1.112:9100: connect: connection refused
```

Thx.

**Comment by sstarcher** [comment]
Sounds like you are using the latest image with an older helm chart.  A PR was merged in for the helm chart a few days ago.  It should be good now let me know.
