### ISSUE TITLE
Runtime error when disabling one of the metrics

### ISSUE THREAD

**Issue by mykolakobzar** [sstarcher/helm-exporter#110]
Hi @sstarcher
When I disable one of the metrics with a command  line or disable it via helm chart values  **"minfo-metric"|"timestamp-metric"|"outdated-metric"** I get this error  
`panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103d77460] `
It looks like the issue is that it's trying to register the metrics which is not initialised if it was disabled
I created a [PR](https://github.com/sstarcher/helm-exporter/pull/109) to fix that.
Thank you!

**Comment by sstarcher** [comment]
Thanks!
