### ISSUE TITLE
vulnerabilites in 1.2.5

### ISSUE THREAD

**Issue by shvkumara** [sstarcher/helm-exporter#113]
Hi,
  We are exploring using helm-exporter in production. As per the need, we need to make the image free from any critical or high vulnerabilities.
 As per the trivy scan result, we updated the below packages 
old packages
```
-       github.com/docker/distribution v2.8.1+incompatible // indirect
-       github.com/docker/docker v20.10.21+incompatible // indirect
```
New packages
```
+       github.com/docker/distribution v2.8.2+incompatible // indirect
+       github.com/docker/docker v20.10.24+incompatible // indirect
```

 But after building image and running with helm chart, we are getting the the below error in the container and it never run successfully. 
```
exec /usr/local/bin/helm-exporter: exec format error
````

**Comment by shvkumara** [comment]
If i reset/remove the changes, then it works but the vulnerabilities will be there and won't get approved to prod.

**Comment by sstarcher** [comment]
Merged https://github.com/sstarcher/helm-exporter/pull/114
Try your scan now
