### ISSUE TITLE
helm_chart_info{} metric not available when chart is in "pending-upgrade" status

### ISSUE THREAD

**Issue by mimmus** [sstarcher/helm-exporter#117]
Hi,
I noticed that an important info (a chart in "pending-upgrade" status) is not available in helm_chart_info{}  metric, only chart in status "1" are available. I queried directly:
 http://host:9571/metrics
endpoint, to exclude issues with Prometheus.

Any suggestion?

**Comment by sstarcher** [comment]
That's interesting you can see here the status code maps https://github.com/sstarcher/helm-exporter/blob/96171583acc7c9e1266dca00b37d35035aa859b2/main.go#L67

Unless the underlying API changed the status code which is possible.

**Comment by mimmus** [comment]
How can I check the status code returned by underlying API?

**Comment by sstarcher** [comment]
Add log lines to the code and run the code

**Comment by mimmus** [comment]
Shane,
this is beyond my capabilities.

**Comment by mimmus** [comment]
Command:
`helm ls -n <namespace>`
by default lists only releases that are deployed or failed. 

To see my releases in "pending-upgrade", I need to add '--all' (or '--pending').
Perhaps, is it true also when calling the API?

**Comment by mimmus** [comment]
Yes, to see also release in "pending-upgrade", you need to add:
```
...
	for _, client := range clients.Items() {
		list := action.NewList(client.(*action.Configuration))
		list.All = true                  <--
		list.SetStateMask()          <--
...
```

**Comment by sstarcher** [comment]
nice work tracking this down.

**Comment by mimmus** [comment]
If possible, please generate a new docker image/helm chart

**Comment by sstarcher** [comment]
done 1.2.8 should generate soon

**Comment by sstarcher** [comment]
Looks like something is wrong with the release process.  I will try and fix it over the weekend.

**Comment by sstarcher** [comment]
I spent some time, but parts of the pipeline are busted and need to be fixed
