### ISSUE TITLE
Possibility to disable chart up-to-date-check

### ISSUE THREAD

**Issue by muffl0n** [sstarcher/helm-exporter#150]
We're currently trying to implement `NetworkPolicies` with `helm-exporter`. As we're using `helm-exporter` just for checking if there are helm-releases in `state != deployed && state != deleted`, there's no need for `helm-exporter` to talk to the internet.

Unfortunately this prevents `helm-exporter` to start at all, cause it's trying to reach `artifacthub.io` which fails. 

Is there a way to disable the up-to-date-check so that `helm-exporter` can work in such a restricted environment?

**Comment by muffl0n** [comment]
Sorry for the noise, I found it: https://github.com/sstarcher/helm-exporter/blob/master/helm/values.yaml#L7
```
latestChartVersion: false
```

Are there any plans to include `NetworkPolicies` in the chart? Are you open for PRs concerning this feature?

**Comment by sstarcher** [comment]
Fully open to PRs.  I don't actively use this tool any longer, but I'll review any PRs and try to get them merged.

**Comment by muffl0n** [comment]
Are you using something else to check the status of your helm releases?

**Comment by sstarcher** [comment]
No, not currently using anything to cover this gap.  Moved to more of a GitOps flow with rendered manifests.
