### ISSUE TITLE
Add Flux support : auto discover registries and chart names

### ISSUE THREAD

**Issue by guyguy333** [sstarcher/helm-exporter#153]
If GitOps is used in combination with [Flux](https://fluxcd.io), Helm registries as well as repository from chart is already defined inside Flux CRDs:

- HelmRepository: https://fluxcd.io/flux/components/source/helmrepositories/
- HelmRelease: https://fluxcd.io/flux/components/helm/helmreleases/

It would be great if Helm Exporter could have an auto discover feature of registries (HelmRepository) and "overrideChartNames" (HelmRelease) from Flux CRDs (if available)

Thus, Helm Exporter would be able to track automagically all deployed Helm charts with Flux.

**Comment by sstarcher** [comment]
That sounds like a great feature. I’m spending minimal time on this
project, but would be happy to accept a PR for features such as this.
