### ISSUE TITLE
Helm Exporter waiting to connect?

### ISSUE THREAD

**Issue by darren-bell-nanthealth** [sstarcher/helm-exporter#16]
Hi
I've tried to deploy the exporter on a kubernetes cluster. I've deployed it in the kube-system namespace where tiller exists. The tiller service is: tiller-deploy.kube-system:44134 TCP

However, in the exporter pod log, all I am seeing is: `Attempting to connect to tiller-deploy.kube-system:44134`. Should I be expecting to see more logs here? I'm unsure how to get any more information to help diagnose the problem as everything appears to be configured correctly.

Thanks

**Comment by sstarcher** [comment]
From a debugging standpoint, I would launch a pod and attempt to telnet to `tiller-deploy.kube-system:44134` to ensure you are able to connect.  If that works I would recommend using kubectl locally to do a port-forward and trying to run the binary locally and helm locally to ensure you are able to hit the endpoint.  The code uses the helm code to do everything so if configured correctly similar to helm it should function the same as the helm client.

**Comment by darren-bell-nanthealth** [comment]
After coming back to this after a break, I realized I had to use the same service account as Tiller, 

Thanks
