### ISSUE TITLE
Image 0.4.1 is broken, please retag current latest with 0.4.2

### ISSUE THREAD

**Issue by benhartley** [sstarcher/helm-exporter#18]
I believe the image currently tagged `latest` contains the fix in this PR: https://github.com/sstarcher/helm-exporter/pull/17

A version tag has not been applied to it yet: https://hub.docker.com/r/sstarcher/helm-exporter/tags

Please could you tag it with `0.4.2`?

**Comment by swade1987** [comment]
This would be extremely useful as we've lost visibility into our helm releases now from this.

**Comment by gavinmcnair** [comment]
Is this likely to get merged soon?

**Comment by sstarcher** [comment]
I was on vacation and just got back.  I'll go tag it now.  Whenever this happens you can always use a specific sha.

**Comment by sstarcher** [comment]
It is now tagged and waiting for docker hub to build.
