### ISSUE TITLE
Expose the value of Revision

### ISSUE THREAD

**Issue by leopoldodonnell** [sstarcher/helm-exporter#19]
Nice project! It exports everything except the Revision value for a release. Exporting the Revsion value would be useful feedback and would provide the complete picture to the prometheus data.

**Comment by sstarcher** [comment]
To do this it would likely make sense to add it as a separate metric vs adding it as a label due to cardinality.  Thoughts?

**Comment by bergerx** [comment]
When i was first checking the project, i was expecting to see the revision as the value and the status as a label.

Revision can go crazy in certain cases, it's definitely not suitable to be a label.
So it make sense to create a new metric with its value as the revision.

This way we could also have the signal to see when a helm upgrade is triggered.

**Comment by sstarcher** [comment]
This has now been released in the latest chart.
