### ISSUE TITLE
Failed to connect: context deadline exceeded

### ISSUE THREAD

**Issue by IngussNeilands** [sstarcher/helm-exporter#21]
Already mentioned in [15](https://github.com/sstarcher/helm-exporter/issues/15) and [16](https://github.com/sstarcher/helm-exporter/issues/16)

When at least one tiller installation (mentioned in tillerNamespaces) doesnot exist - helm exporter enters CrashLoopBackOff state with error message `Failed to connect: context deadline exceeded`

Expected - working state for any available tillers, specific unable to connect metric output for the ones that are unavailable.

Not sure if this is feature request or bug report ;)

**Comment by sstarcher** [comment]
Somewhere between a feature and a bug report :)

**Comment by sstarcher** [comment]
should fix it - https://github.com/sstarcher/helm-exporter/pull/22
