### ISSUE TITLE
Support for Helm v3

### ISSUE THREAD

**Issue by coultenholt** [sstarcher/helm-exporter#23]
Do you plan on supporting Helm v3?

**Comment by sstarcher** [comment]
I have not looked into how I would support helm v3, but I'm certainly interested in doing so.

**Comment by sstarcher** [comment]
https://github.com/sstarcher/helm-exporter/pull/24

**Comment by coultenholt** [comment]
So this has been merged now?

**Comment by sstarcher** [comment]
yes
