### ISSUE TITLE
Helm exporter doesn't work with prometheus-operator

### ISSUE THREAD

**Issue by krystian-kulgawczuk** [sstarcher/helm-exporter#28]
Error I'm getting:
    
    Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/name" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector]

exporter chart version: 0.5.0
stable prometheus-operator chart version: 8.7.0

Configuration used:

    serviceMonitor:
      create: true
      namespace: monitoring

**Comment by sstarcher** [comment]
This should now be resolved with #29
