### ISSUE TITLE
spec.endpoints.port: Invalid value: \"integer\"

### ISSUE THREAD

**Issue by onedr0p** [sstarcher/helm-exporter#31]
Thanks for the updates! Having an issue with the servicemonitor:

```
ts=2020-04-03T15:54:43.063494079Z caller=release.go:216 component=release release=helm-exporter targetNamespace=monitoring resource=monitoring:helmrelease/helm-exporter helmVersion=v3 error="Helm release failed" revision=63f9e4417f552597d9545aae52d3f556cd9d977a err="failed to upgrade chart for release [helm-exporter]: ServiceMonitor.monitoring.coreos.com \"helm-exporter\" is invalid: spec.endpoints.port: Invalid value: \"integer\": spec.endpoints.port in body must be of type string: \"integer\""
```

See my deployment here:
https://github.com/onedr0p/k3s-gitops/blob/master/deployments/monitoring/helm-exporter/helm-exporter.yaml

**Comment by sstarcher** [comment]
Try quoting the port https://github.com/onedr0p/k3s-gitops/blob/master/deployments/monitoring/helm-exporter/helm-exporter.yaml#L25

**Comment by onedr0p** [comment]
I believe endpoint should be a port label, not the port itself.

See this issue:
https://github.com/coreos/prometheus-operator/issues/416

**Comment by onedr0p** [comment]
To be clear, quoting did not work

**Comment by sstarcher** [comment]
ahh thank you

**Comment by onedr0p** [comment]
See my custom deployment to understand on how to make a proper ServiceMonitor:

https://github.com/onedr0p/k3s-gitops/blob/master/deployments/monitoring/sonarr-exporter/sonarr-exporter.yaml

**Comment by sstarcher** [comment]
I just set this on master try changing your 
serviceMonitor:
  port: http

**Comment by sstarcher** [comment]
Try 0.5.5 it should fix this issue, but I have not had time to test it out.

**Comment by onedr0p** [comment]
You didn't change anything to the chart, it won't work. Please review my fork and make the adjusted changes to fix the issue. If not, I will try to get to opening a PR with my changes sometime.

**Comment by sstarcher** [comment]
It was changed - https://github.com/sstarcher/helm-exporter/blob/master/helm/templates/servicemonitor.yaml#L16

**Comment by onedr0p** [comment]
Man my days are blending, sorry about that. I'll give it a shot.

**Comment by sstarcher** [comment]
No problem at all.  I should have been more clear the commit that fixed it was not directly on 0.5.5

**Comment by mogggggg** [comment]
Hi @sstarcher, I can't seem to get this working - I'm running version `0.5.5+cb6f3a1` and my serviceMonitor configuration looks like this:

```
serviceMonitor:
  create: true
  namespace: monitoring
  additionalLabels:
    app: helm-exporter
    prometheus: kube-prometheus
    release: prometheus-operator
```

When I try and apply I get the following error:

```
spec.endpoints.port in body must be of type string: "integer"
```

Am I missing something?

**Comment by sstarcher** [comment]
You are not missing something.  I thought it was in 0.5.5, but it was a change I made after 0.5.5.  It's on the head of master.  I'm releasing it now as 0.5.6.  Once the release shows up I'll verify it and close this issue.

**Comment by sstarcher** [comment]
0.5.6 is verified to resolve that issue.
