### ISSUE TITLE
Is it possible to limit clusterrole access in helm chart?

### ISSUE THREAD

**Issue by mrueg** [sstarcher/helm-exporter#35]
Hi @sstarcher 
Why does helm-exporter require clusterwide access to secrets in https://github.com/sstarcher/helm-exporter/blob/master/helm/templates/role.yaml#L13 ?

Would it be possible to limit the access to namespaces only?

**Comment by sstarcher** [comment]
For helm 3 it would need secret access to any namespace that has a helm chart running in it as helm stores data as secrets by default in Helm 3.

**Comment by mrueg** [comment]
Thanks for the quick response!
I guess there's no (easy) way to limit this to only helm secrets.

**Comment by sstarcher** [comment]
If the user used a different storage mechanism than a secret we could move to that, but if it's stored in a secret we are limited to needing access.

**Comment by mrueg** [comment]
https://github.com/helm/helm/pull/8272 I've sent in a PR to helm that might help to reduce the permission to "list".
