### ISSUE TITLE
Generate the metrics on scrape and not in predefined interval

### ISSUE THREAD

**Issue by dannyk81** [sstarcher/helm-exporter#4]
Me again ;)

I was looking at the code and it seems that the metrics are being generated and stored every 30 seconds, later served to Prometheus when the exporter is scraped.

although this shouldn't have any meaningful difference given the kind of information this exposed here, it somewhat goes against Prometheus best practices that state that metrics should be collected during the scrape process and not be collected in advance.

reference: https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling

**Comment by sstarcher** [comment]
done - https://github.com/sstarcher/helm-exporter/commit/aadddfdaf7c605aba6d8b1cb0e74039a7eeb711e
