### ISSUE TITLE
Tag a new version with a corresponding docker image

### ISSUE THREAD

**Issue by jfrabaute** [sstarcher/helm-exporter#48]
As this new change https://github.com/sstarcher/helm-exporter/commit/5d9086f4ebe17b3356e5df694cb46986514eb913 is integrated in the helm chart, having a version tagged would be great, so we can avoid using "latest" and use an immutable tag.

Would it be possible to tag a new version of the app?

Thank you very much !

**Comment by shanestarcher-okta** [comment]
Done let me know if `0.7.0` does not show up.

**Comment by sstarcher** [comment]
done let me know if `0.7.0` does not show up
