### ISSUE TITLE
Not correct namespace is displayed in Grafana

### ISSUE THREAD

**Issue by leonids2005** [sstarcher/helm-exporter#49]
After installing the exporter, the namespace where the exporter is installed displayed in the namespace column.
Obviously, I expect to see a namespace where the chart is installed.

**Comment by shanestarcher-okta** [comment]
Can you post the metrics coming from the helm exporter here

**Comment by leonids2005** [comment]
I understand what is the problem - imo, exported_namespace should be shown in the table and not the namespace where exported is installed.
I have one more question - what will be great is to have the time what the chart was actually updated. there is an "updated" field that should be properly formatted in Grafana. Probably most of the comments are for Grafana dashboard

**Comment by shanestarcher-okta** [comment]
@leonids2005 nothing can be done about the scrape duration if it's done in line during the call.  The latest released version can optionally do it in the background so the scrape is instantaneous. If you look at the metric over time you should essentially get a history outside of that I'm not sure how you would store that in a time series metric.

**Comment by leonids2005** [comment]
Thank you, I was able to achieve what I wanted. so we should close this issue. thank you
