### ISSUE TITLE
Consider changing the port number to something else

### ISSUE THREAD

**Issue by dannyk81** [sstarcher/helm-exporter#5]
Currently the exporter listens on port 9100, which is reserved for node-exporter.

In general, there's no impact here, but to avoid confusion/etc I think it would be advisable to use a differ port number here.

https://github.com/prometheus/prometheus/wiki/Default-port-allocations

Thanks! and again... sorry for all the issues/feedback... hope you won't find this as noise 😄

**Comment by sstarcher** [comment]
9157 - done https://github.com/sstarcher/helm-exporter/commit/aadddfdaf7c605aba6d8b1cb0e74039a7eeb711e
