### ISSUE TITLE
Include grafana dashboard into the chart

### ISSUE THREAD

**Issue by bergerx** [sstarcher/helm-exporter#50]
It would really be helpful if the grafana dashboard could be included into the chart. So users with the kube-prometheus-stack/grafana dashboard may have it out of the box without having to install it manually from grafana website. 

A similar suggestion and implementation pllan can be found here:
https://github.com/kubernetes/ingress-nginx/issues/6381

**Comment by shanestarcher-okta** [comment]
That's a great idea

**Comment by sstarcher** [comment]
That's a great idea!

**Comment by dirien** [comment]
@sstarcher, can you u assign this to me? When finished the other PR I can tackle this.
