### ISSUE TITLE
How to specify tiller helm list intervals?

### ISSUE THREAD

**Issue by mechaHarry** [sstarcher/helm-exporter#52]
Which part of the values.yaml are we supposed to modify so that tiller only lists every x seconds?

We are using version 0.3.0 (quite old but the only version that supports helm 2 for us) and no adjustment of values.yaml has allowed the exporter to trigger any interval other than 30 seconds.

As our clusters scale, this causes large cpu usage, especially since it lists twice for some reason at every interval and triggers our prometheus alerts.

**Comment by shanestarcher-okta** [comment]
Only the latest code in helm 3 supports listing every x seconds instead of doing in in serial.

**Comment by mechaHarry** [comment]
Okay, thank you for the update.
