### ISSUE TITLE
Missing helm charts found - Failed to search chart info

### ISSUE THREAD

**Issue by albrookesplowman** [sstarcher/helm-exporter#68]
I have just tried using this little tool as I think it does exactly what we want for some modules that we have installed on our kubernetes clusters.  I am trying to find a list of all the versions on the installed modules in different clusters that we have developed and then display this is Grafana.

However, when I start the pod I get a lot of messages such as 

time="2021-10-05T06:03:39Z" level=error msg="Failed to search chart info" chart=XXXXX error=EOF

And this seems to be for all the charts of the internal modules that we have developed.  Is there something that we need to add to our helm charts so that the deployments are recognisable by your exporter? An annotation for example...  

Many thanks

**Comment by sstarcher** [comment]
@albrookesplowman do no metrics show up?  With that error, you should still have all of your chart data shown.

`Failed to search chart info` means that it has searched `https://artifacthub.io/` and found multiple charts that match your current chart.

**Comment by sstarcher** [comment]
A major refactor of this just released.  Can you try version 1.0.0 or 1.0.1(will be released in about 10 mins)

**Comment by sstarcher** [comment]
For 1.0.0 > you can see - https://github.com/sstarcher/helm-exporter#configuration-for-latest-versions

**Comment by albrookesplowman** [comment]
I think the problem is that we don't have our helm charts stored in a helm repository so it doesn't know how to get the information.  We utilise the Azure Container Registry to store the built containers before they are pulled to the kubernetes cluster so are we able to link into that somehow?

**Comment by sstarcher** [comment]
Currently, it only supports reading from a index.yaml that is accessible via HTTP.  You can disable latest version fetching by specifying `-latest-chart-version=false`

**Comment by sstarcher** [comment]
In helm it's `latestChartVersion: false`

**Comment by albrookesplowman** [comment]
So, if I create a yaml file which is available via a URL then the exporter will pick up the data from there and display it in Prometheus.. so if we keep the file up to date whenever we deploy new versions, it should all work. Is that correct? Are there docs on the format of the yaml file? Your help has been amazing!

**Comment by sstarcher** [comment]
So the yaml file is only needed if you want `helm-exporter` to be able to output when your applications are out of date.  It can output the current versions and such without that yaml file.

The yaml file is a helm index file that helm uses to process helm registries.   This is an example of one created by helm - https://github.com/sstarcher/helm-charts/blob/master/docs/index.yaml

**Comment by albrookesplowman** [comment]
Hi - i have just tried to pull 1.0.1 and I am getting an image not found error from docker.io/sstarcher/helm-exporter:1.0.1

**Comment by sstarcher** [comment]
Let me check docker hub it may not have published yet.

**Comment by sstarcher** [comment]
...I forgot dockerhub nixed it's free automated builds

**Comment by sstarcher** [comment]
@albrookesplowman try again

**Comment by albrookesplowman** [comment]
that works.... Where does the version come from in the helm information? I have done a helm list on some of my charts and I see a chart name of admin-api-53398 and an app version of 1.0.  However in the grafana dashboard I see a version of 53.40k so I assume that it is pulling that from the last bit of the chart name (53398).  Is there any way of getting the actual app version 1.0) into the dashboard as the version?

**Comment by sstarcher** [comment]
You can see from the README.md https://github.com/sstarcher/helm-exporter#format
That the appVersion should be available in the metrics.  You should be able to update the grafana dashboard to show it.
