### ISSUE TITLE
Deploy the chart to a repository

### ISSUE THREAD

**Issue by alanpearce** [sstarcher/helm-exporter#7]
Currently it appears that the only way to get the chart is by cloning the git repository.

Would it be possible to publish the chart to kubeapps, or to host a chart repository somewhere public? That way, it would be very easy for users to keep up to date and avoid creating or researching issues that were already solved in a previous release.

**Comment by sstarcher** [comment]
The chart is now available as part of the standard stable/helm-exporter from https://github.com/helm/charts

Does this solve your issue? If not please re-open.
