### ISSUE TITLE
Metric value question

### ISSUE THREAD

**Issue by gminiba** [sstarcher/helm-exporter#76]
Hi! 
What is this * 1000 for? https://github.com/sstarcher/helm-exporter/blob/master/main.go#L150
I'm using the metric value to compare it with time() in Prometheus and cannot get the reason it's multiplied by 1000 in the exporter.
If you don't mind I want to create a PR to make it possible to get the metric without this multiplication with the optional parameter. The default behavior is not to change.

**Comment by sstarcher** [comment]
When comparing it in prometheus can you multiply time() by 1000?

**Comment by gminiba** [comment]
Sure I can, but it looks strange to me

**Comment by sstarcher** [comment]
This was the original request as Grafana looks to use the default format of milliseconds - https://github.com/sstarcher/helm-exporter/pull/10

So they have the opposite issue that you have.  It's not going to be possible to make every tool happy.  Luckily Prometheus can support multiplication, but Grafana does not support changing the format.
