### ISSUE TITLE
OCI registry support

### ISSUE THREAD

**Issue by jholm117** [sstarcher/helm-exporter#83]
Are there plans to support OCI registries instead of the index.yaml classic repos?

**Comment by dtwilliamsWork** [comment]
doesn't seem to work with Karpenter

`
- registry:
          url: 'oci://public.ecr.aws/karpenter'
          secretRef:
            name: "karpenter-repo-secret"
            userKey: "username"
            passKey: "password"
`

**Comment by hugosxm** [comment]
@sstarcher still no plan for this ? I have a couple of chart in oci format like thanos and dragonflydb-operator

**Comment by sstarcher** [comment]
I'm not contributing features to this project.  If someone would like to pickup the work I can review it and merge it in.
