### ISSUE TITLE
Update Helm chart for helm-exporter

### ISSUE THREAD

**Issue by naiduarvind** [sstarcher/helm-exporter#9]
I have created a[ PR here](https://github.com/helm/charts/pull/13034) to update the Helm chart to the latest version to address the exposing of appVersion which was closed 14 hours ago -- I was about to push the code in the morning when I realised you have made a commit and deployed it.

However, I don't see a new version of Docker image tagged as I am only seeing the latest tag. Could you tag the latest image of helm-exporter and let me know here soI can address the PR over in helm/charts?

**Comment by sstarcher** [comment]
I just released 0.3.0
